### ISSUE TITLE
Add "UTC" to time column labels

### ISSUE THREAD

**Issue by narthur** [k-szuster/luci-access-control#22]
It's easy to miss that the times need to be in UTC. Why not label the columns as "Start time UTC" and "End time UTC"?

**Comment by k-szuster** [comment]
UTC time is used in OpenWRT-CC (15) only, which was already mentioned before. Both OpenWRT-BB (14) and newer releases (after may 2017) interpret times correctly. 
There is no simple solution to this problem, since the bug comes with CCs kernel. I wouldn't like to create separate package for that single version.

**Comment by narthur** [comment]
@k-szuster Thanks for the clarification, that makes total sense. Closing.
