### ISSUE TITLE
Not working on OpenWrt Chaos Calmer 15.05 

### ISSUE THREAD

**Issue by almottier** [k-szuster/luci-access-control#7]
I installed the package with opkg, but I don't have "Access control " in the Menu...

**Comment by cpinkham** [comment]
I'm not sure if it is the right fix, but I was able to get the menu entry to show up on my 15.05.1 system by editting /usr/lib/lua/luci/controller/access_control.lua and changing the page setup to look like this:

        page = node("admin", "network", "access_control")   
        page.target = cbi("access_control")              
        page.title  = _("Access Control")                
        page.order  = 70

**Comment by k-szuster** [comment]
This change does not make any difference.
Maybe you forgot to reboot or at least, restart HTTP server?
Many users confirmed the program worked on 15.05.

**Comment by cpinkham** [comment]
Thanks.

I restarted uhttpd several times, but did not reboot since it wasn't mentioned in the README.md.  I couldn't reboot the router at the time to test that.  I just did the following test:

- remove package
- reboot
- confirm menu entry gone
- reinstall package
- confirm menu entry did not exist
- restart uhttpd
- confirm menu entry did not exist
- reboot
- confirm menu entry shows up

So, the appears the reboot is currently required.  Can you update the README.md file to indicate that a reboot should be performed after installing the package?

**Comment by k-szuster** [comment]
Good remark. Actually the reboot is not necessary, but it's the simplest way to get things working,  so I'll amend the guide.
